### ISSUE TITLE
Cant use DirectURL function

### ISSUE THREAD

**Issue by lioliy** [XUJINKAI/aria2-with-webui#1]
I want download my files from a remote server.
However,I received a 404 Not Found Error.

For instance
```
Not Found

The URL you requested (/cha-cha.mp4) was not found.
Generated by darkhttpd/1.12 on Sun, 01 Jan 2017 02:10:36 GMT
```

I tried change url to /data/_dl,but still have this problem

```
Not Found

The URL you requested (/data/_dl/cha-cha.mp4) was not found.
Generated by darkhttpd/1.12 on Sun, 01 Jan 2017 02:15:45 GMT
```

Your project is great.Could add or fix this function?

DirectURL: [https://github.com/ziahamza/webui-aria2/blob/master/directurl.md](url)

**Comment by XUJINKAI** [comment]
fixed. please delete and redownload image, port 6888 is exposed to browse /data folder now.
