### ISSUE TITLE
建议取消下载完成后自动移动的功能

### ISSUE THREAD

**Issue by starrin-zz** [XUJINKAI/aria2-with-webui#11]
在使用插件导出115或者百度盘的文件夹时，插件会遍历目标文件夹，并为里面的每一个文件分别创建下载任务，同时保留文件夹结构。下载完成后自动移动的功能会把所有结果文件都堆叠到根目录下，导致文件夹结构完全丢失。

**Comment by XUJINKAI** [comment]
https://github.com/XUJINKAI/aria2-with-webui/blob/master/files/aria2.conf#L2
你修改配置把这行删掉就行了
