### ISSUE TITLE
Aria2 WebUI options not saved in /conf/aria2.conf

### ISSUE THREAD

**Issue by devedetti** [XUJINKAI/aria2-with-webui#3]
Hi! I'm new here and I does not know how WebUI works.

But I have a volume for /conf and the changes made from WebUI (ie: upload / download speed) is not persist after container reboot.

Can you address me about that? Thanks!

Creation mode:
```
sudo docker volume create aria_web
sudo docker run -d --name aria_web -p 6800:6800 -p 6880:80 -p 6888:8080 -v /mnt/raid/samba/storage/aria:/data -v aria_web:/conf -e SECRET=abcd xujinkai/aria2-with-webui
```

**Comment by XUJINKAI** [comment]
yes, any changes in webui will reset after reboot. You should edit aria2.conf file for persistant change.

webui runs in sandbox in your browser, it can't edit files directly. And aria2 not support edit config file through rpc.

https://github.com/ziahamza/webui-aria2/issues/60  
https://github.com/ziahamza/webui-aria2/issues/341

**Comment by devedetti** [comment]
Thanks for your time!
