### ISSUE TITLE
关于https

### ISSUE THREAD

**Issue by wnark** [XUJINKAI/aria2-with-webui#4]
因为我的vps采用了全局https的设计，但您的docker无法用https访问
例如https://baidu.com:6500 是直接不能访问的，而用http://baidu.com:6500能访问
请问如何使得网页控制可以使用https访问
谢谢

**Comment by XUJINKAI** [comment]
https是要你在vps上设置证书和本地转发的，webui不提供，当然也没法直接用https访问。
比如你webui是http://127.0.0.1:8000, 在vps上设置证书还有来源是本地8000端口，目标端口443，这样访问https://127.0.0.1:443就行了。注意http://127.0.0.1:8000仍然是http，两个不冲突，中间多了一道手续。

我没试验过，也不推荐，因为webui还要和aria2通信，https下aria2能不能通信也是个问题。https://github.com/ziahamza/webui-aria2/issues/108
