### ISSUE TITLE
最新版docker开启rpc-secret cpu 狂飚

### ISSUE THREAD

**Issue by ChicBrother** [XUJINKAI/aria2-with-webui#6]
开发者你好，
非常感谢你的docker作品。使用很方便，但我发现只要我在conf里面添加 一行 

rpc-secret=token 

这条配置启用 token 后，虽然客户端可以连接上去，但是docker容量看到cpu一路狂飚，一直在30%左右（未开始下载作业 )。

只要删除这条配置就回到1%左右，目前切到了使用用户名与密码的鉴权方式。请问想修改到token的认证方式是否还有需要配置的地方？

**Comment by XUJINKAI** [comment]
应该是没差的，我也是在conf里添加实现的。
